name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-support:
    name: Lint and set up test-support
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5
        with:
          python-version: "3.13"

      - run: |
          uv python install
          uv pip install modal ruff

      - run: |
          ruff check test-support/
          ruff format --check test-support/

      - run: test-support/setup.sh
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
          MODAL_ENVIRONMENT: libmodal
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1


  js:
    name: modal-js build, lint, and test
    runs-on: ubuntu-latest
    needs: test-support

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: "22"

      - run: npm ci
        working-directory: ./modal-js

      - run: npm run format:check
        working-directory: ./modal-js

      - run: npm run check
        working-directory: ./modal-js

      - run: npm run lint
        working-directory: ./modal-js

      - run: npm run build
        working-directory: ./modal-js

      - run: npm test
        working-directory: ./modal-js
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
          MODAL_ENVIRONMENT: libmodal

  go:
    name: modal-go build, lint, and test
    runs-on: ubuntu-latest
    needs: test-support

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.24"
          cache-dependency-path: modal-go/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
        with:
          version: v2.1.5
          working-directory: ./modal-go

      - run: go test -v -count=1 -parallel=10 ./...
        working-directory: ./modal-go
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
          MODAL_ENVIRONMENT: libmodal
