name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-24.04
    if: startsWith(github.event.head_commit.message, '[RELEASE] Prepare release for')
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        submodules: true

    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: "20.x"
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        cache-dependency-path: modal-js/package-lock.json

    - name: Install npm packages
      run: npm install
      working-directory: ./modal-js

    - name: Config git user
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Publish and push tags
      run: |
        python ci/release.py publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
