name: Open PR for release

on:
  workflow_dispatch:
    inputs:
      update:
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  open-pr-for-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: modal-js/package-lock.json

    - name: Install npm packages
      run: npm install
      working-directory: ./modal-js


    - name: Config git user
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Make release commits
      run: |
        python ci/release.py version ${{ inputs.update }}

    - name: Populate metadata for pull request
      run: |
        echo "MY_TITLE='Title for release'" >> $GITHUB_ENV


    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        title: ${{ env.MY_TITLE }}


    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
